"""add default value for fixed supporter and message

Revision ID: bb5afd3abb8e
Revises: edb804202c7b
Create Date: 2024-09-10 20:33:23.120539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5afd3abb8e'
down_revision = 'edb804202c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_supporter', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('fixed_message', sa.String(length=256), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('fixed_message_word')
        batch_op.drop_column('fixed_supporter_word')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_supporter_word', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fixed_message_word', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('fixed_message')
        batch_op.drop_column('fixed_supporter')

    # ### end Alembic commands ###
